language: python
sudo: false
python: 2.7

before_install:
  - rvm install 2.3
  - rvm use 2.3
  - gem install hiptest-publisher
  - hiptest-publisher -c python-unittest.conf --only=tests --test-run-id=459281

script:
 - python bootstrap.py
 - bin/buildout
 - bin/test --with-xunit

after_script:
  - hiptest-publisher -c python-unittest.conf --push="nosetests.xml" --test-run-id=459281
